version: '3'
services:
  mypostgres:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgpool2:
    image: do/pgpool2-alpine:latest
    build: 
      context: .
    depends_on: 
      - mypostgres
    environment:
      - PGPOOL_BACKENDS=1:mypostgres:5432
    ports:
      - 5432:5432/tcp